# Generated by Django 5.1 on 2024-08-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="files",
            old_name="name",
            new_name="filename",
        ),
        migrations.RemoveField(
            model_name="files",
            name="encodedFile",
        ),
        migrations.AddField(
            model_name="files",
            name="filedata",
            field=models.FileField(default="", upload_to="files"),
        ),
    ]
