# Generated by Django 5.1 on 2024-08-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_files_filedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queries",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("query", models.CharField(max_length=2000)),
            ],
        ),
    ]
